In [1]:
import numpy as np
import pandas as pd

data_path = '../basic_data'

### 日频数据

In [2]:
# 读取数据
return_daily = pd.read_pickle(f'{data_path}/daily/ret.pkl')
return_daily

,000001.SZ,000002.SZ,000004.SZ,000005.SZ,000006.SZ,000007.SZ,000008.SZ,000009.SZ,000010.SZ,000011.SZ,...,688787.SH,688788.SH,688789.SH,688793.SH,688798.SH,688799.SH,688800.SH,688819.SH,688981.SH,689009.SH
datetime,,,,,,,,,,,,,,,,,,,,,
2015-01-05,0.011364,0.072662,0.007707,NaN,0.004255,-0.005479,-0.017655,NaN,NaN,0.012024,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-06,-0.014981,-0.036888,0.049076,NaN,-0.032486,-0.017218,0.005991,NaN,NaN,-0.034653,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-07,-0.019011,-0.009053,-0.003038,NaN,0.001460,0.022425,0.022904,0.029344,NaN,0.014359,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-08,-0.033592,-0.044975,0.031079,NaN,-0.011662,-0.000685,0.031796,0.001500,NaN,-0.025278,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-09,0.008021,-0.010302,-0.028960,NaN,-0.011799,-0.005487,0.005642,-0.027715,NaN,-0.019710,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-01-09,0.003279,0.006110,-0.026928,-0.009346,-0.006757,0.000000,0.004348,0.000000,0.012658,-0.023543,...,0.023097,0.020391,0.004468,0.006300,-0.008237,-0.003883,-0.029717,0.024981,-0.021212,0.018035
2024-01-10,-0.009804,-0.014170,0.020755,-0.028302,-0.009070,-0.010526,-0.004329,0.000866,0.025000,-0.004592,...,-0.021970,-0.023816,-0.018111,-0.008537,0.021761,-0.009311,-0.023404,0.010499,-0.020227,0.029024
2024-01-11,0.008801,0.002053,0.038817,0.029126,0.034325,0.017021,0.008696,0.011246,0.060976,0.017301,...,0.030674,0.026641,-0.005393,-0.000574,0.034303,0.003497,0.049112,0.024119,0.002738,0.035897
2024-01-12,0.002181,-0.006148,-0.049229,-0.009434,-0.013274,-0.025105,0.000000,0.001711,-0.014368,-0.001134,...,-0.029460,-0.022398,0.008676,-0.006318,-0.041182,-0.002832,-0.010716,0.003261,-0.037185,-0.026874
2024-01-15,0.002176,0.001031,-0.017467,0.047619,0.011211,-0.006438,-0.004310,0.004270,-0.067055,0.012486,...,-0.039647,-0.012853,0.040641,-0.006647,0.009672,0.006772,-0.015108,-0.011195,-0.003491,0.002544

In [3]:
# 日频基础算子函数
def roll_skew(factor, window):
    return factor.rolling(window,min_periods=3).skew()

def roll_wmean(factor, weight, window):
    return (factor*weight).rolling(window,min_periods=1).sum() / weight.rolling(window,min_periods=1).sum()

def roll_mean(factor, window):
    return factor.rolling(window,min_periods=2).mean()

In [4]:
# 日频因子函数
def factor_daily_001(return_daily):
    ret_skew = roll_skew(return_daily, 10)
    ret_mean = roll_mean(return_daily, 10)
    factor = roll_wmean(ret_mean, ret_skew , 10)
    return factor

factor1 = factor_daily_001(return_daily=return_daily)
factor1

/home/yzh/miniconda3/envs/alpha_310/lib/python3.10/site-packages/pandas/core/window/rolling.py:611: RuntimeWarning: All-NaN slice encountered
  return func(x, start, end, min_periods, *numba_args)

,000001.SZ,000002.SZ,000004.SZ,000005.SZ,000006.SZ,000007.SZ,000008.SZ,000009.SZ,000010.SZ,000011.SZ,...,688787.SH,688788.SH,688789.SH,688793.SH,688798.SH,688799.SH,688800.SH,688819.SH,688981.SH,689009.SH
datetime,,,,,,,,,,,,,,,,,,,,,
2015-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-07,-0.007543,0.008907,0.017915,NaN,-0.008924,-0.000091,0.003747,NaN,NaN,-0.002757,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-08,-0.009866,0.001524,0.018493,NaN,-0.009197,-0.000160,0.008040,NaN,NaN,-0.003098,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-09,-0.009866,-0.001097,0.018837,NaN,-0.009407,-0.000581,0.008497,0.001043,NaN,-0.001280,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-01-09,0.001373,-0.003108,-0.020672,-0.005603,-0.004470,0.000449,-0.004141,0.000285,-0.004508,-0.035789,...,-0.010799,0.006683,-0.002988,0.003553,-0.006005,-0.005958,-0.000962,0.001129,0.008702,-0.009963
2024-01-10,0.001028,-0.003099,0.031724,-0.003579,-0.003793,0.000877,-0.004106,0.000385,-0.004995,0.006502,...,-0.010388,0.003106,-0.003584,0.004258,-0.005790,-0.004829,-0.002201,0.003124,-0.073045,-0.008143
2024-01-11,0.001080,-0.003021,0.006083,0.002587,-0.003492,0.001101,-0.003430,0.000711,-0.001626,0.003210,...,-0.010362,0.002953,-0.004472,0.004422,-0.005727,-0.004613,-0.002170,0.008552,-0.016560,-0.007565
2024-01-12,0.000671,-0.003215,0.003404,0.003928,-0.002891,0.001661,-0.002968,0.001320,0.002753,0.001485,...,-0.012004,0.005598,-0.004499,0.005331,-0.005451,-0.004248,-0.003255,-0.010879,-0.011929,-0.007529
2024-01-15,0.000415,-0.003276,0.003116,0.004393,-0.002339,0.002439,-0.002244,0.050033,0.004418,0.000760,...,-0.010650,0.059367,-0.004127,0.005438,-0.004871,-0.003797,-0.005182,-0.004992,-0.009570,-0.008581

### min频数据

In [9]:
# 读取数据
turnover_5min = pd.read_pickle(f'{data_path}/5min/turnover_float.pkl')
turnover_5min

,000001.SZ,000002.SZ,000004.SZ,000005.SZ,000006.SZ,000007.SZ,000008.SZ,000009.SZ,000010.SZ,000011.SZ,...,688787.SH,688788.SH,688789.SH,688793.SH,688798.SH,688799.SH,688800.SH,688819.SH,688981.SH,689009.SH
datetime,,,,,,,,,,,,,,,,,,,,,
2015-01-05 09:35:00+08:00,0.002209,0.014300,0.000758,NaN,0.006313,0.001084,0.000661,NaN,NaN,0.008864,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-05 09:40:00+08:00,0.001430,0.004759,0.000734,NaN,0.003436,0.000490,0.002531,NaN,NaN,0.004966,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-05 09:45:00+08:00,0.000914,0.002914,0.000397,NaN,0.002223,0.000521,0.000960,NaN,NaN,0.003740,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-05 09:50:00+08:00,0.000862,0.003708,0.000539,NaN,0.003753,0.000474,0.000367,NaN,NaN,0.005015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-05 09:55:00+08:00,0.001124,0.004519,0.000675,NaN,0.006515,0.001184,0.000255,NaN,NaN,0.009766,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-01-15 14:40:00+08:00,0.000051,0.000041,0.000694,0.001151,0.000116,0.000031,0.000025,0.000063,0.000923,0.000143,...,0.000255,0.000054,0.000111,0.000422,0.000158,0.000073,0.000054,0.000173,0.000120,0.000016
2024-01-15 14:45:00+08:00,0.000127,0.000092,0.001254,0.000469,0.000127,0.000059,0.000064,0.000046,0.003137,0.000069,...,0.000628,0.000154,0.000295,0.000178,0.000111,0.000228,0.000042,0.000283,0.000205,0.000006
2024-01-15 14:50:00+08:00,0.000048,0.000075,0.000728,0.000982,0.000143,0.000076,0.000050,0.000057,0.004172,0.000137,...,0.000429,0.000158,0.000109,0.001352,0.000103,0.000127,0.000122,0.000358,0.000093,0.000010
2024-01-15 14:55:00+08:00,0.000085,0.000279,0.001032,0.000322,0.000375,0.000021,0.000038,0.000134,0.002597,0.000251,...,0.001214,0.000033,0.000230,0.001584,0.000221,0.000352,0.000181,0.000389,0.000100,0.000013
2024-01-15 15:00:00+08:00,0.000133,0.000113,0.001067,0.000889,0.000960,0.000348,0.000080,0.000333,0.003872,0.000760,...,0.000495,0.000150,0.000111,0.001581,0.000056,0.000310,0.000205,0.000261,0.000112,0.000022

In [10]:
# min频基础算子
def skew(factor):
        return_df = factor.groupby(factor.index.date).skew()
        return_df.index = pd.to_datetime(return_df.index).strftime("%Y-%m-%d")
        return return_df

def mean(factor):
        return_df = factor.groupby(factor.index.date).mean()
        return_df.index = pd.to_datetime(return_df.index).strftime("%Y-%m-%d")
        return return_df

In [11]:
# min因子算子
def factor_5min_001(turnover_5min):
    ret_skew = skew(turnover_5min)
    ret_mean = mean(turnover_5min)
    factor = roll_wmean(ret_mean, ret_skew , 10)
    return factor

factor2 = factor_5min_001(turnover_5min=turnover_5min)
factor2

,000001.SZ,000002.SZ,000004.SZ,000005.SZ,000006.SZ,000007.SZ,000008.SZ,000009.SZ,000010.SZ,000011.SZ,...,688787.SH,688788.SH,688789.SH,688793.SH,688798.SH,688799.SH,688800.SH,688819.SH,688981.SH,689009.SH
2015-01-05,0.000606,0.001413,0.000698,NaN,0.001678,0.000288,0.000324,NaN,NaN,0.002368,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-06,0.000543,0.001125,0.000761,NaN,0.001201,0.000279,0.000372,NaN,NaN,0.001853,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-07,0.000474,0.001055,0.000684,NaN,0.000997,0.000259,0.000355,0.001018,NaN,0.001541,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-08,0.000430,0.000979,0.000753,NaN,0.000863,0.000246,0.000348,0.000945,NaN,0.001401,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-09,0.000441,0.000968,0.000737,NaN,0.000808,0.000224,0.000338,0.000903,NaN,0.001320,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-01-09,0.000105,0.000136,0.001099,0.000315,0.000488,0.000064,0.000161,0.000115,0.000894,0.000275,...,0.000606,0.000081,0.000164,0.000537,0.000172,0.000562,0.000255,0.000338,0.000166,0.000199
2024-01-10,0.000109,0.000139,0.001256,0.000293,0.000478,0.000062,0.000163,0.000115,0.001414,0.000275,...,0.000586,0.000077,0.000170,0.000565,0.000190,0.000503,0.000278,0.000344,0.000167,0.000177
2024-01-11,0.000111,0.000147,0.001385,0.000291,0.000440,0.000062,0.000164,0.000119,0.001936,0.000290,...,0.000589,0.000080,0.000178,0.000556,0.000194,0.000486,0.000281,0.000352,0.000169,0.000200
2024-01-12,0.000105,0.000147,0.001444,0.000285,0.000413,0.000065,0.000163,0.000136,0.002512,0.000281,...,0.000562,0.000081,0.000166,0.000513,0.000195,0.000424,0.000260,0.000325,0.000174,0.000197
2024-01-15,0.000102,0.000153,0.001417,0.000294,0.000413,0.000065,0.000140,0.000137,0.002752,0.000279,...,0.000592,0.000082,0.000163,0.000534,0.000189,0.000398,0.000252,0.000308,0.000177,0.000188

#### 无论用什么频段的数据，最终因子值都需要变成日频。
#### 接下来参考backtest包，自行进行因子回测。