In [1]:
from Operator import *

# 实例化
operator = Operator()

start_day = '2019-01-01'
end_day = '2023-12-19'

In [2]:
# 日数据算子：有roll_前缀
return_daily = pd.read_pickle('/daily/ret.pkl').loc[start_day:end_day]
return_daily

,000001.SZ,000002.SZ,000004.SZ,000005.SZ,000006.SZ,000007.SZ,000008.SZ,000009.SZ,000010.SZ,000011.SZ,...,688787.SH,688788.SH,688789.SH,688793.SH,688798.SH,688799.SH,688800.SH,688819.SH,688981.SH,689009.SH
datetime,,,,,,,,,,,,,,,,,,,,,
2019-01-02,-0.020256,0.003358,0.001871,-0.003731,-0.005791,0.007444,-0.002571,-0.002320,0.006135,0.016340,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-03,0.009793,0.007113,0.011831,0.003745,0.000000,-0.035714,-0.010309,-0.013954,0.000000,0.007503,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-04,0.050647,0.035729,0.021538,0.026119,0.021359,0.021711,0.018229,0.030660,0.012195,0.017021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-07,-0.001026,0.004813,0.037349,0.032727,0.015209,0.007500,0.040921,0.018307,0.024096,0.026151,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-08,-0.008214,-0.001996,-0.023809,-0.003521,-0.003745,-0.026055,0.017199,0.015730,-0.008824,-0.007136,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-13,-0.027601,-0.033606,-0.022637,-0.024194,-0.012371,0.000000,-0.004016,-0.006706,-0.015152,-0.015957,...,-0.002463,-0.018126,-0.041762,-0.024793,-0.012778,-0.002427,-0.017079,-0.012195,-0.006837,-0.021075
2023-12-14,-0.001092,-0.013158,-0.016213,-0.049587,0.014614,0.004057,-0.008065,-0.008439,0.003077,0.014054,...,-0.039126,-0.001560,-0.018423,0.006721,0.008212,-0.019668,-0.015361,0.001411,-0.012093,-0.007800
2023-12-15,0.006557,0.013333,-0.012360,-0.034783,0.002058,0.006061,0.000000,-0.008511,-0.012270,0.004264,...,-0.000642,-0.005208,0.007164,0.001451,-0.024020,0.034747,0.014322,-0.000352,0.009416,-0.013208
2023-12-18,-0.008686,-0.009399,-0.014303,0.009009,-0.022587,-0.020080,-0.012195,0.000000,-0.012422,-0.021231,...,0.014524,-0.027487,-0.009819,-0.009565,-0.027440,-0.036578,-0.031518,-0.025018,0.002612,0.000000
2023-12-19,-0.003286,-0.015180,0.014510,0.000000,-0.010504,-0.012295,-0.008230,0.001717,-0.006289,-0.010846,...,0.002280,0.019919,-0.018517,0.002634,0.004363,0.025934,0.009893,-0.007589,0.018980,-0.011154

In [13]:
# 计算20日收益峰度
operator.roll_kurt(factor=return_daily,window=20)
# 计算20日收益最大值
operator.roll_max(factor=return_daily,window=20)

close_daily = pd.read_pickle('/daily/close.pkl').loc[start_day:end_day]
# 计算20日收盘价最大回撤率
operator.max_downup_rate_day(factor=close_daily,window=20,drawdown=True)

industry_l1 = pd.read_pickle('/daily/l1_indus.pkl').bfill().ffill() # 行业数据若存在缺失值，需要填充缺失值
# 计算一级行业分类横截面均值
operator.sample_classify_mean(factor=return_daily, classify=industry_l1)
# 剔除一级行业风格影响
operator.factor_sample_classify(factor=return_daily, classify_list=[industry_l1], corr_period=20, method="mean")

In [5]:
# min数据算子：无roll_前缀
return_5min = pd.read_pickle('/5min/ret.pkl').loc[start_day:end_day]
return_5min

,000001.SZ,000002.SZ,000004.SZ,000005.SZ,000006.SZ,000007.SZ,000008.SZ,000009.SZ,000010.SZ,000011.SZ,...,688787.SH,688788.SH,688789.SH,688793.SH,688798.SH,688799.SH,688800.SH,688819.SH,688981.SH,689009.SH
datetime,,,,,,,,,,,,,,,,,,,,,
2019-01-02 09:35:00+08:00,-0.003198,0.003358,0.001248,0.003731,0.005792,0.007444,-0.005141,0.013921,0.000000,0.010893,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-02 09:40:00+08:00,-0.004264,0.002519,0.006238,0.000000,0.005792,0.003722,-0.007712,0.009281,-0.003067,0.009804,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-02 09:45:00+08:00,-0.005331,0.003358,0.001248,0.000000,0.013514,-0.003722,-0.005141,0.006961,0.003067,0.028322,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-02 09:50:00+08:00,-0.012793,0.007137,0.001248,0.000000,0.007722,-0.002481,-0.002571,0.018561,0.000000,0.022876,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-02 09:55:00+08:00,-0.012793,0.001259,0.003743,0.003731,0.000000,-0.001241,0.002571,0.016241,0.000000,0.020697,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-19 14:40:00+08:00,0.001101,0.001940,0.000000,0.009091,0.002141,-0.006198,0.000000,0.000861,0.000000,0.001101,...,0.004233,0.001857,-0.000727,0.000588,0.001458,0.000814,0.002601,0.001103,0.000919,0.002916
2023-12-19 14:45:00+08:00,0.000000,0.000968,0.000000,0.000000,0.002137,0.006237,0.004184,0.001720,0.003185,-0.001100,...,0.000639,-0.001853,0.005301,0.000588,0.003203,0.000203,0.003891,0.002203,0.003304,0.000646
2023-12-19 14:50:00+08:00,0.001100,0.000967,0.001794,0.000000,0.000000,0.002066,-0.004167,0.000000,-0.003175,0.001101,...,0.002042,0.003979,0.002689,0.002939,0.001451,0.005490,0.000775,0.002565,0.000366,-0.000969
2023-12-19 14:55:00+08:00,0.000000,0.001932,0.001194,0.009009,0.000000,-0.002062,0.004184,0.000000,0.003185,0.002200,...,0.003057,-0.001585,0.000412,0.001172,0.000290,-0.001011,0.000000,0.001096,0.001280,0.001293
2023-12-19 15:00:00+08:00,0.000000,0.000964,0.000596,0.000000,0.004264,-0.004132,0.004167,0.001717,0.003175,0.001098,...,0.004699,0.002646,-0.000103,0.002634,0.000580,0.001012,0.001549,0.002556,0.000183,0.001614

In [14]:
# 计算5min数据日内时序排名
operator.tsrank_min(factor=return_5min,pct=True)
# 计算1日5min峰度
operator.kurt(factor=return_5min)
# 计算1日5min最大值
operator.max(factor=return_5min)

turnover_5min = pd.read_pickle('/5min/turnover_float.pkl').loc[start_day:end_day]
# 计算一日13:05-15:00，5min换手率均值
operator.part_mean(factor=turnover_5min, begin_time='13:05', end_time='15:00')

close_5min = pd.read_pickle('/5min/close.pkl').loc[start_day:end_day]
# 计算1日5min收盘价最大涨幅
operator.max_downup_rate_min(factor=close_5min, drawdown=False)

In [15]:
# 将daily数据repeat至 1min or 5min数据
return_daily = pd.read_pickle('/daily/ret.pkl').loc[start_day:end_day]
return_5min =  pd.read_pickle('/5min/ret.pkl').loc[start_day:end_day]
index_5min = return_5min.index

operator.repeat_min(factor=return_daily, min_date_name=index_5min, begin_time='09:35', end_time='15:00')

,000001.SZ,000002.SZ,000004.SZ,000005.SZ,000006.SZ,000007.SZ,000008.SZ,000009.SZ,000010.SZ,000011.SZ,...,688787.SH,688788.SH,688789.SH,688793.SH,688798.SH,688799.SH,688800.SH,688819.SH,688981.SH,689009.SH
datetime,,,,,,,,,,,,,,,,,,,,,
2019-01-02 09:35:00+08:00,-0.020256,0.003358,0.001871,-0.003731,-0.005791,0.007444,-0.002571,-0.002320,0.006135,0.016340,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-02 09:40:00+08:00,-0.020256,0.003358,0.001871,-0.003731,-0.005791,0.007444,-0.002571,-0.002320,0.006135,0.016340,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-02 09:45:00+08:00,-0.020256,0.003358,0.001871,-0.003731,-0.005791,0.007444,-0.002571,-0.002320,0.006135,0.016340,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-02 09:50:00+08:00,-0.020256,0.003358,0.001871,-0.003731,-0.005791,0.007444,-0.002571,-0.002320,0.006135,0.016340,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-02 09:55:00+08:00,-0.020256,0.003358,0.001871,-0.003731,-0.005791,0.007444,-0.002571,-0.002320,0.006135,0.016340,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-19 14:40:00+08:00,-0.003286,-0.015180,0.014510,0.000000,-0.010504,-0.012295,-0.008230,0.001717,-0.006289,-0.010846,...,0.00228,0.019919,-0.018517,0.002634,0.004363,0.025934,0.009893,-0.007589,0.01898,-0.011154
2023-12-19 14:45:00+08:00,-0.003286,-0.015180,0.014510,0.000000,-0.010504,-0.012295,-0.008230,0.001717,-0.006289,-0.010846,...,0.00228,0.019919,-0.018517,0.002634,0.004363,0.025934,0.009893,-0.007589,0.01898,-0.011154
2023-12-19 14:50:00+08:00,-0.003286,-0.015180,0.014510,0.000000,-0.010504,-0.012295,-0.008230,0.001717,-0.006289,-0.010846,...,0.00228,0.019919,-0.018517,0.002634,0.004363,0.025934,0.009893,-0.007589,0.01898,-0.011154
2023-12-19 14:55:00+08:00,-0.003286,-0.015180,0.014510,0.000000,-0.010504,-0.012295,-0.008230,0.001717,-0.006289,-0.010846,...,0.00228,0.019919,-0.018517,0.002634,0.004363,0.025934,0.009893,-0.007589,0.01898,-0.011154
2023-12-19 15:00:00+08:00,-0.003286,-0.015180,0.014510,0.000000,-0.010504,-0.012295,-0.008230,0.001717,-0.006289,-0.010846,...,0.00228,0.019919,-0.018517,0.002634,0.004363,0.025934,0.009893,-0.007589,0.01898,-0.011154